printversion:
  build: ./jruby-1.7.23
  command: ruby -v
server:
  build: ./jruby-1.7.23
  volumes:
    - .:/home
  working_dir: /home
  command: ruby scripts/server.rb
  ports:
    - 8088:8088
client1:
  build: ./jruby-1.7.23
  volumes:
    - .:/home
  working_dir: /home
  command: ruby scripts/client.rb
  links:
    - server
client2:
  build: ./jruby-1.7.23
  volumes:
    - .:/home
  working_dir: /home
  command: ruby scripts/client.rb
  links:
    - server
